# Change these first
owner: AndyWebServices # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Home Assistant
    url: https://ha.andywebservices.com
  - name: FreeIPA
    url: https://auth.andywebservices.com
    icon: https://www.freeipa.org/_static/favicon.png
  - name: Unifi
    url: https://unifi.andywebservices.com
    icon: https://unifi.ui.com/favicon.ico
  - name: AndyWebServices Certificate Authority
    url: https://awsca.aws
    icon: https://smallstep.com/favicon.ico
    expectedStatusCodes:
      - 404
  - name: Pihole
    url: https://pihole.aws
    icon: https://pi-hole.net/favicon.ico
  - name: Octoprint
    url: https://octoprint.aws
    icon: https://octoprint.org/assets/img/tentacle-20x20.png
  - name: Grocy
    url: https://grocy.aws
    icon: https://raw.githubusercontent.com/grocy/grocy/b26dfe3fb090f5ffdce7d11b75dde4a7901eaffd/public/img/icon.svg

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.andywebservices.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "AndyWebServices status monitor, powered by [Upptime](https://github.com/upptime/upptime)"
  introMessage: This page tracks the uptime of internal and external services provided by AndyWebServices.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
